name: Test IDAKLUSolver

on:
  push:
  workflow_dispatch:
    
jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - name: Install dependencies
      run: sudo apt install libopenblas-dev gcc gfortran
    - name: Clone PyBaMM
      run: |
        python -m pip install wheel
        git clone -b develop --single-branch https://github.com/pybamm-team/PyBaMM
    - name: Install casadi cmake numpy
      run: python -m pip install cmake casadi numpy
    - name: Install Sundials KLU and PyBaMM
      run: |
        pip install wget
        cd PyBaMM
        python ./scripts/install_KLU_Sundials.py
        git clone https://github.com/pybind/pybind11.git ./pybind11
        python -m pip install . 
    - name: Test
      run: python -c "import pybamm; pybamm.IDAKLUSolver()"
      
